#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# --- BEGIN_HEADER ---
#
# client - lustre backup helpers
# Copyright (C) 2020-2026 The lustrebackup Project by the Science HPC Center at UCPH
#
# This file is part of lustrebackup.
#
# lustrebackup is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# lustrebackup is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# -- END_HEADER ---
#

"""This module contains various lustre snapshots helpers
used for creating, listing and mounting snapshots on the client"""

import os
import datetime
import time
import re
import tempfile
import psutil


from lustrebackup.shared.base import print_stderr, force_unicode
from lustrebackup.shared.defaults import last_snapshot_name, \
    snapshot_dirname, snapshot_name_format, snapshot_created_format
from lustrebackup.shared.fileio import pickle, unpickle, \
    path_join, makedirs_rec, make_symlink, remove_dir, \
    release_file_lock, make_temp_file, move, delete_file
from lustrebackup.shared.lock import acquire_snapshot_lock
from lustrebackup.shared.shell import shellexec
from lustrebackup.snapshot.mgs import snapshot_list_mgs, \
    mount_snapshot_mgs, umount_snapshot_mgs


def __add_snapshot_dict(configuration,
                        snapshot,
                        snapshot_dict):
    """Add snapshot to snapshot dict with timestamp as key"""
    logger = configuration.logger
    snapshot_name = snapshot.get('snapshot_name', '')
    if not snapshot_name:
        logger.error("Missing 'snapshot_name' in snapshot: %s" % snapshot)
        return False
    create_time = snapshot.get('create_time', '').strip()
    if not create_time:
        logger.error("Missing 'create_time' in snapshot: %s" % snapshot)
        return False
    # NOTE: lustre doesn't list 'comment' if empty
    if 'comment' not in snapshot.keys():
        snapshot['comment'] = ''

    # If target snapshot then extract source information from comment

    source_re = re.compile("^source_fsname: ([a-z|0-9|._-]+)"
                           + ", source_snapshot: ([0-9]{10})"
                           + ", source_start_recno: ([0-9]+)"
                           + ", source_end_recno: ([0-9]+)"
                           + ", source_largefile_size: ([0-9]+)"
                           + ", source_hugefile_size: ([0-9]+)$")
    source = source_re.fullmatch(snapshot.get('comment', ''))
    if source and len(source.groups()) == 6:
        snapshot['source'] = {'fsname': source.group(1),
                              'snapshot': source.group(2),
                              'start_recno': source.group(3),
                              'end_recno': source.group(4),
                              'largefile_size': source.group(5),
                              'hugefile_size': source.group(6),
                              }
    # NOTE: The source lustre fsname is used as snapshot name
    #       at both source and target
    snapshot_fsname = configuration.lustre_fsname
    if snapshot.get('source', {}).get('fsname', ''):
        snapshot_fsname = snapshot['source']['fsname']
    lustrebackup_pattern = snapshot_name_format \
        % {'fsname': snapshot_fsname,
           'timestamp': "([0-9]+)"}
    # NOTE: To support old legacy '-auto-' snapshot name format
    lustrebackup_pattern = lustrebackup_pattern.replace(
        '-backup-', '-(backup|auto)?-')
    lustrebackup_re = re.compile(lustrebackup_pattern)
    lustrebackup_ent = lustrebackup_re.fullmatch(snapshot_name)
    # NOTE: We use timestamp from snapshot name if snapshot was generated by
    #       lustrebackup, otherwise lustre snapshot create time
    if lustrebackup_ent:
        lustrebackup_snapshot = True
        timestamp = int(lustrebackup_ent.group(2))
    else:
        lustrebackup_snapshot = False
        datetime_elm \
            = datetime.datetime.strptime(create_time,
                                         snapshot_created_format)
        timestamp = int(time.mktime(datetime_elm.timetuple()))
    snapshot['timestamp'] = timestamp
    snapshot['lustrebackup'] = lustrebackup_snapshot
    snapshot_dict[timestamp] = snapshot

    return True


def create_snapshots_dict(configuration,
                          snapshot_timestamp=None,
                          snapshot_name=None,
                          persistent=False,
                          do_lock=True,
                          verbose=False):
    """Retrieve snapshot list from MGS
    if *persistent* is True
    the snapshot dict is pickled to disk and the filepath is returned
    if *persistent* is False then the snapshot dict is return
    if *snapshot_name* is None and *snapshot_timestamp* is set
    then *snapshot_name* is resolved from *snapshot_timestamp*
    """
    logger = configuration.logger
    meta_basepath = configuration.lustre_meta_basepath
    snapshot_path = path_join(configuration,
                              meta_basepath,
                              snapshot_dirname,
                              convert_utf8=False)

    # Acquire snapshot lock

    if do_lock:
        lock = acquire_snapshot_lock(configuration)
        if not lock:
            logger.error("Failed to acquire snapshot lock")
            return None

    # Create snapshot path if it doesn't exists

    if not os.path.isdir(snapshot_path):
        status = makedirs_rec(configuration, snapshot_path)
        if not status:
            msg = "Failed to create snapshot_path: %r" \
                % snapshot_path
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None

    # Create tempfile for mgs raw result

    (snapshot_raw_temp_fd, snapshot_raw_temp_filepath) \
        = make_temp_file(dir=snapshot_path)

    # resolve list_snapshot_name from snapshot_timestamp if needed and possible
    # NOTE: If both snapshot_timestamp and snapshot_name are None
    #       then list_snapshot_name is left None and the full snapshot list
    #       is retrieved from the MGS

    list_snapshot_name = snapshot_name
    if list_snapshot_name is None and snapshot_timestamp is not None:
        list_snapshot_name = snapshot_name_format \
            % {'fsname': configuration.lustre_fsname,
               'timestamp': snapshot_timestamp}

    # For a specific snapshot we allow missing
    # NOTE: This occur if the snapshot was destroyed

    allow_missing_snapshot = False
    if snapshot_name is not None:
        allow_missing_snapshot = True

    # Fetch snapshot list from MGS

    (retval, _) \
        = snapshot_list_mgs(configuration,
                            snapshot_name=list_snapshot_name,
                            snapshot_list_filepath=snapshot_raw_temp_filepath,
                            allow_missing_snapshot=allow_missing_snapshot,
                            verbose=verbose)
    if not retval:
        msg = "Failed to fetch snapshot list from MGS, list_snapshot_name: %s" \
            % list_snapshot_name \
            + ", snapshot_timestamp: %s" \
            % snapshot_timestamp
        logger.error(msg)
        if verbose:
            print_stderr("ERROR: %s" % msg)
        return None

    # Create snapshots dict

    snapshots_dict = {}
    try:
        fh = open(snapshot_raw_temp_filepath, 'r')
        # Parse raw MGS snapshot list and create dict of key/value pairs
        # Each snapshot is added to snapshots_dict with timestamp as key
        snapshot = {}
        line = fh.readline()
        while line:
            s_line = line.rstrip()
            # logger.debug("%s" % s_line)
            if s_line:
                entry = s_line.split(": ")
                snapshot[entry[0]] = ": ".join(entry[1:])
            elif snapshot:
                __add_snapshot_dict(configuration,
                                    snapshot,
                                    snapshots_dict)
                snapshot = {}
            line = fh.readline()
        __add_snapshot_dict(configuration,
                            snapshot,
                            snapshots_dict)
        fh.close()
    except Exception as err:
        msg = "Failed to parse snapshot list: %r, error: %s" \
            % (snapshot_raw_temp_filepath, err)
        logger.error(msg)
        if verbose:
            print_stderr("ERROR: %s" % msg)
        return None

    # Update last snapshot dict if requested
    # NOTE: If 'list_snapshot_name' is None then a complete list is fetched
    #       into 'snapshots_dict' and therefore we do not sync
    #       with 'last_snapshots_dict'
    if list_snapshot_name is not None:
        last_snapshots_dict = get_snapshots(configuration, do_lock=False)
        # Resolve snapshot_timestamp if not provided
        check_snapshot_timestamp = snapshot_timestamp
        if check_snapshot_timestamp is None and list_snapshot_name:
            for timestamp, snapshot in last_snapshots_dict.items():
                if snapshot.get('snapshot_name', '') == list_snapshot_name:
                    check_snapshot_timestamp = timestamp
        # Update last snapshots dict with new values
        if snapshots_dict:
            logger.debug(
                "updating last_snapshots_dict with snapshot: %s" % snapshots_dict)
            last_snapshots_dict.update(snapshots_dict)
        # check if snapshot with 'check_snapshot_timestamp' was removed
        if check_snapshot_timestamp is not None \
                and check_snapshot_timestamp not in snapshots_dict \
                and check_snapshot_timestamp in last_snapshots_dict:
            logger.debug("deleting snapshot with timestamp: %d" %
                         check_snapshot_timestamp)
            del last_snapshots_dict[check_snapshot_timestamp]
        snapshots_dict = last_snapshots_dict

    if persistent is False:
        # Remove raw tempfile
        if snapshot_raw_temp_fd is not None:
            os.close(snapshot_raw_temp_fd)
        status = delete_file(configuration,
                             snapshot_raw_temp_filepath,
                             allow_missing=True,
                             logger=logger)
        if not status:
            msg = "Failed to remove snapshot raw tempfile: %r" \
                % snapshot_raw_temp_filepath
            logger.warning(msg)
            if verbose:
                print_stderr("WARNING: %s" % msg)
    else:
        # Get last snapshot timestamp

        sorted_snapshot_timestamps = sorted(list(snapshots_dict))
        if not sorted_snapshot_timestamps:
            msg = "No snapshots found in snapshot list: %r" \
                % snapshot_raw_temp_filepath \
                + " for snapshot_name: %s" % list_snapshot_name
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None
        last_snapshot_timestamp = sorted_snapshot_timestamps[-1]

        # Move snapshot_raw_temp_filepath to filepath matching pickled dict
        raw_temp_filename = os.path.basename(snapshot_raw_temp_filepath)
        snapshot_raw_filepath = path_join(configuration,
                                          snapshot_path,
                                          "%d.raw.%s" \
                                          % (last_snapshot_timestamp,
                                          raw_temp_filename),
                                          convert_utf8=False)

        status = move(configuration,
                      snapshot_raw_temp_filepath,
                      snapshot_raw_filepath,
                      logger=logger)
        if not status:
            msg = "Failed to move snapshot raw tempfile %r -> %r" \
                % (snapshot_raw_temp_filepath, snapshot_raw_filepath)
            logger.warning(msg)
            if verbose:
                print_stderr("WARNING: %s" % msg)

        # Pickle snapshot dict

        snapshot_pck_filepath = path_join(configuration,
                                          snapshot_path,
                                          "%d.pck" % last_snapshot_timestamp,
                                          convert_utf8=False)
        logger.debug("saving snapshot dict to: %r" % snapshot_pck_filepath)
        retval = pickle(configuration,
                        snapshots_dict,
                        snapshot_pck_filepath)
        if not retval:
            msg = "Failed to save snapshots dict to: %r" \
                % snapshot_pck_filepath
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None

        # Create last_snapshot symlink to new snapshot_pck_filepath

        if retval:
            rel_snapshot_info_path \
                = path_join(configuration,
                            snapshot_dirname,
                            os.path.basename(snapshot_pck_filepath))
            retval = make_symlink(configuration,
                                  rel_snapshot_info_path,
                                  last_snapshot_name,
                                  working_dir=meta_basepath,
                                  force=True)
        if not retval:
            msg = "Failed to create last snapshot symlink (%r -> %r) in %r" \
                % (rel_snapshot_info_path,
                   snapshot_pck_filepath,
                   meta_basepath)
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None

    if persistent:
        result = snapshot_pck_filepath
    else:
        result = snapshots_dict

    # Release lock

    if do_lock:
        lock_status = release_file_lock(configuration, lock)
        if not lock_status:
            retval = False
            logger.error("Failed to release snapshot lock")

    return result


def get_inprogress_snapshots(configuration,
                             snapshots=None,
                             do_lock=True):
    """Return inprogress snapshots"""
    logger = configuration.logger
    meta_basepath = configuration.lustre_meta_basepath
    # Acquire snapshot lock
    if do_lock:
        lock = acquire_snapshot_lock(configuration)
        if not lock:
            logger.error("Failed to acquire snapshot lock")
            return (False, None)
    if not snapshots:
        snapshots = get_snapshots(configuration, do_lock=False)
    # Resolve inprogress snapshots
    inprogress_source_re = re.compile("^inprogress_(.*)")
    inprogress_target_re = re.compile("^([a-z]*)/([0-9]*)\\.pck")
    retval = True
    result = {}
    with os.scandir(meta_basepath) as it:
        for entry in it:
            inprogress_source_ent = inprogress_source_re.fullmatch(entry.name)
            if inprogress_source_ent:
                inprogress_type = inprogress_source_ent.group(1)
                inprogress_target_filepath = os.readlink(entry.path)
                inprogress_target_ent \
                    = inprogress_target_re.fullmatch(
                        inprogress_target_filepath)
                if not inprogress_target_ent:
                    retval = False
                    logger.error("Malformed inprogress entry: %r"
                                 % entry.name
                                 + "type: %s, src: %r, dest: %r"
                                 % (inprogress_type,
                                    entry.path,
                                    inprogress_target_filepath))
                    break
                inprogress_timestamp = int(inprogress_target_ent.group(2))
                inprogress_snapshot = snapshots.get(inprogress_timestamp, None)
                # NOTE: If target backup is in progress,
                #       then there is no inprogress snapshot
                if inprogress_snapshot is not None:
                    result[inprogress_timestamp] = inprogress_snapshot
                else:
                    logger.warning("No inprogress snapshot found for: %r"
                                   % entry.name
                                   + "type: %s, src: %r, dest: %r"
                                   % (inprogress_type,
                                      entry.path,
                                      inprogress_target_filepath))

    # Release lock

    if do_lock:
        lock_status = release_file_lock(configuration, lock)
        if not lock_status:
            retval = False
            logger.error("Failed to release snapshot lock")

    return (retval, result)


def get_snapshots(configuration,
                  snapshot_filename=last_snapshot_name,
                  before_timestamp=int(time.time()),
                  after_timestamp=0,
                  do_lock=True,
                  verbose=False):
    """Return dict (stored on backupmeta client) with snapshots info"""
    logger = configuration.logger
    meta_basepath = configuration.lustre_meta_basepath

    # Acquire snapshot lock

    if do_lock:
        lock = acquire_snapshot_lock(configuration)
        if not lock:
            msg = "get_snapshots: " \
                + "Failed to acquire snapshot lock"
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None

    #
    if snapshot_filename == last_snapshot_name:
        snapshots_filepath = path_join(configuration,
                                       meta_basepath,
                                       last_snapshot_name)
    else:
        snapshots_filepath = path_join(configuration,
                                       meta_basepath,
                                       snapshot_dirname,
                                       snapshot_filename)
    snapshots = unpickle(configuration, snapshots_filepath)
    if snapshots is None:
        result = None
        msg = "Missing or malformed snapshot file: %r" % snapshots_filepath
        logger.error(msg)
        if verbose:
            print_stderr("ERROR: %s" % msg)
    else:
        result = {timestamp: snapshot
                  for timestamp, snapshot in snapshots.items()
                  if timestamp > after_timestamp
                  and timestamp < before_timestamp}

    # Release lock

    if do_lock:
        lock_status = release_file_lock(configuration, lock)
        if not lock_status:
            msg = "get_snapshots: " \
                + "Failed to release snapshot lock"
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)

    return result


def get_snapshot(configuration,
                 metalink_name=None,
                 timestamp=None,
                 verbose=False):
    """Return last snapshot dict"""
    logger = configuration.logger
    snapshot_timestamp = 0
    if metalink_name is not None:
        meta_basepath = configuration.lustre_meta_basepath
        metalink_filepath = path_join(configuration,
                                      meta_basepath,
                                      metalink_name)
        metalink_pck_re = re.compile("([0-9]*)\\.pck")
        # NOTE: Checks if link exist and if target file exists
        if not os.path.isfile(metalink_filepath):
            msg = "Missing %s: %r" % (metalink_name, metalink_filepath)
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None

        metalink_pck = force_unicode(os.readlink(metalink_filepath))
        metalink_ent = metalink_pck_re.search(metalink_pck)
        if not metalink_ent.group(1):
            msg = "Failed to resolve %s timestamp from: %r" \
                % (metalink_name, metalink_pck)
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None
        try:
            snapshot_timestamp = int(metalink_ent.group(1))
        except Exception as err:
            msg = "Failed to resolve %s timestamp from: %r, error: %s" % (
                metalink_name,
                metalink_pck,
                err,
            )
            logger.error(msg)
            if verbose:
                print_stderr("ERROR: %s" % msg)
            return None
    elif timestamp:
        snapshot_timestamp = timestamp

    snapshot_dict = create_snapshots_dict(configuration,
                                          snapshot_timestamp=snapshot_timestamp)
    snapshot = None
    if snapshot_dict is not None:
        snapshot = snapshot_dict.get(snapshot_timestamp, None)

    return snapshot


def get_mountpoints(configuration, snapshot, postfix=os.getpid()):
    """Returns a list of active mountpoints for *snapshot* with *postfix*"""
    logger = configuration.logger
    snapshot_fsname = snapshot.get('snapshot_fsname', '')
    if not snapshot_fsname:
        logger.error("Missing snapshot_fsname in snapshot: %s"
                     % snapshot)
        return (None, False)

    result = []
    os_mounts = psutil.disk_partitions(all=True)
    for mount in os_mounts:
        if mount.fstype == "lustre" \
                and mount.device.find(snapshot_fsname) > -1:
            if postfix and mount.mountpoint.endswith(str(postfix)):
                result.append(mount.mountpoint)
            elif not postfix:
                result.append(mount.mountpoint)

    return result


def mount_snapshot(configuration,
                   snapshot,
                   postfix=os.getpid(),
                   do_lock=True):
    """Mount snapshot and return a tuple:
    (mountpoint, umount), where umount is a bool telling
    if caller is responsible for umount
    (mount point didn't exist in advance)"""

    logger = configuration.logger
    result = (None, False)

    # If MGS mount failed the return early
    if snapshot.get('client', '') == 'failed':
        logger.debug("Previous mount failed: %s" % snapshot)
        return (None, False)
    snapshot_fsname = snapshot.get('snapshot_fsname', '')
    if not snapshot_fsname:
        logger.error("Missing snapshot_fsname in snapshot: %s"
                     % snapshot)
        return (None, False)
    snapshot_name = snapshot.get('snapshot_name', '')
    if not snapshot_name:
        logger.error("Missing snapshot_name in snapshot: %s"
                     % snapshot)
        return (None, False)

    # Add postfix (default PID) to mountpouint to enable mount/umount
    # from different processes

    mountpoint = path_join(configuration,
                           configuration.lustre_snapshot_home,
                           "%s.%s"
                           % (snapshot_name,
                              postfix)).decode()
    if os.path.ismount(mountpoint):
        return (mountpoint, False)

    # Get lock before mounting

    if do_lock:
        lock = acquire_snapshot_lock(configuration)
        if not lock:
            logger.error("Failed to acquire snapshot lock")
            return (None, False)

    # Check if snapshot was mounted while waiting for lock

    if os.path.ismount(mountpoint):
        snapshot['status'] = 'mounted'
        snapshot['client'] = 'mounted'
        lock_status = release_file_lock(configuration, lock)
        if not lock_status:
            logger.error("Failed to release lock")
        return (mountpoint, True)

    # Mount on MGS if needed

    if snapshot.get('status', '') != 'mounted':
        mgs_retval = mount_snapshot_mgs(configuration,
                                        snapshot_name)
        if mgs_retval:
            snapshot['status'] = 'mounted'
        else:
            snapshot['status'] = 'not mount'
            snapshot['client'] = 'failed'
        # Update snapshot list after MGS mount
        create_snapshots_dict(configuration,
                              snapshot_name=snapshot_name,
                              persistent=True,
                              do_lock=False,)

    # mount snapshot locally

    if snapshot.get('client', '') != 'failed':
        status = makedirs_rec(configuration, mountpoint)
        if not status:
            snapshot['client'] = 'failed'
            logger.error("Failed to create local mountpoint: %r"
                         % mountpoint)
            result = (None, False)
    if snapshot.get('client', '') != 'failed':
        mount_opts = "-o ro,noatime"
        if configuration.lustre_snapshot_mount_opts:
            mount_opts += ",%s" % configuration.lustre_snapshot_mount_opts
        mount_cmd = "mount -t lustre %s %s:/%s %s" \
            % (mount_opts,
               configuration.lustre_nid,
               snapshot_fsname,
               mountpoint)
        # logger.debug(mount_cmd)
        (mount_rc, _, err) = shellexec(configuration, mount_cmd)
        if mount_rc == 0:
            result = (mountpoint, True)
        else:
            snapshot['client'] = 'failed'
            logger.error("Failed to mount snapshot: %r, error: %s"
                         % (snapshot_fsname, err))

        # Disable Lazy Size on MDT (LSoM)
        # NOTE: LSoM updates on (RO) snapshots stalls MDT
        # Disable xattr
        # NOTE: xattr_cache=0 is experimental,
        #       Check if client xattr is actually causing
        #       mdd_attr_set calls on MDT?
        if mount_rc == 0:
            lsom_off_cmd = "lctl set_param mdc.%s-%s-*.mdc_lsom=off" \
                % (snapshot_fsname, configuration.lustre_mdt)
            (lsom_off_rc, _, lsom_off_err) = shellexec(
                configuration, lsom_off_cmd)
            logger.debug("%r: %d" % (lsom_off_cmd, lsom_off_rc))

            xattr_off_cmd = "lctl set_param llite.%s-*.xattr_cache=0" \
                % snapshot_fsname
            (xattr_off_rc, _, xattr_off_err) \
                = shellexec(configuration, xattr_off_cmd)
            logger.debug("%r: %d" % (xattr_off_cmd, xattr_off_rc))

            if lsom_off_rc == 0 and xattr_off_rc == 0:
                snapshot['client'] = 'mounted'
            else:
                snapshot['client'] = 'failed'
                if lsom_off_rc != 0:
                    logger.error("Failed %r: %d, error: %s"
                                 % (lsom_off_cmd,
                                    lsom_off_rc,
                                    lsom_off_err))
                if xattr_off_rc != 0:
                    logger.error("Failed %r: %d, error: %s"
                                 % (xattr_off_cmd,
                                    xattr_off_rc,
                                    xattr_off_err))

    # Release lock

    if do_lock:
        lock_status = release_file_lock(configuration, lock)
        if not lock_status:
            result = (mountpoint, False)
            logger.error("Failed to release snapshot lock")

    return result


def umount_snapshot(configuration,
                    snapshot,
                    postfix=os.getpid(),
                    force=False,
                    update_snapshot_list=True,
                    do_lock=True):
    """Umount local snapshots
    and on MGS server (if required)"""
    logger = configuration.logger
    retval = True
    umounted = []

    snapshot_fsname = snapshot.get('snapshot_fsname', '')
    if not snapshot_fsname:
        logger.error("Missing snapshot_name in snapshot: %s"
                     % snapshot)
        return (False, None)
    snapshot_name = snapshot.get('snapshot_name', '')
    if not snapshot_name:
        logger.error("Missing snapshot_name in snapshot: %s"
                     % snapshot)
        return (False, None)

    if do_lock:
        lock = acquire_snapshot_lock(configuration)
        if not lock:
            logger.error("Failed to acquire snapshot lock")
            return (False, None)

    mountpoints = get_mountpoints(configuration,
                                  snapshot,
                                  postfix=postfix)

    # If not mounted then return early

    if not mountpoints:
        if do_lock:
            lock_status = release_file_lock(configuration, lock)
            if not lock_status:
                logger.error("Failed to release lock")
        return (True, [])

    for mountpoint in mountpoints:
        # Kill processes that has open files in mount
        if force:
            for proc in psutil.process_iter(['pid', 'open_files']):
                for open_file in proc.info['open_files']:
                    if open_file.path.startswith(mountpoint):
                        logger.debug("Trying to kill process: %d, openfile: %r"
                                     % (proc.pid, open_file.path))
                        try:
                            process = psutil.Process(proc.pid)
                            process.kill()
                            process.wait()
                        except psutil.NoSuchProcess:
                            logger.debug("no such process pid: %d"
                                         % proc.pid)
                        except Exception as err:
                            logger.error("umount_snapshot: "
                                         + " Failed to kill %d, error: %s"
                                         % (proc.pid, err))
        # umount through shell
        umount_cmd = "umount %s" % mountpoint
        (umount_rc, _, err) = shellexec(configuration, umount_cmd)
        if umount_rc == 0:
            umounted.append(mountpoint)
        elif umount_rc != 0:
            retval = False
            logger.error("Failed to umount lustre: %r snapshot: %r"
                         % (snapshot_fsname,
                            snapshot_name)
                         + ", mountpoint: %r, error: %s"
                         % (mountpoint, err))
        # remove mount dir
        status = remove_dir(configuration, mountpoint)
        if not status:
            retval = False
            logger.error("Failed to remove lustre: %r snapshot: %r"
                         % (snapshot_fsname,
                            snapshot_name)
                         + ", mountpoint: %r"
                         % mountpoint)

    # Umount snapshot on MGS if no more mountpoints on this client

    remaining_mounts = get_mountpoints(configuration,
                                       snapshot,
                                       postfix=None)
    if not remaining_mounts:
        retval = umount_snapshot_mgs(configuration,
                                     snapshot)
        if not retval:
            logger.error("Failed to MGS umount snapshot: %s"
                         % snapshot_name)
        snapshot['status'] = 'not mount'
        snapshot['client'] = 'not mount'
        # Update snapshot list after MGS mount
        if update_snapshot_list:
            create_snapshots_dict(configuration,
                                  snapshot_name=snapshot_name,
                                  persistent=True,
                                  do_lock=False)
    else:
        logger.info("safe_umount_snapshot_mgs:"
                    + " Skipping MGS umount for %s"
                    % (snapshot_fsname)
                    + ", Found remaining snapshot mounts (%d): %s"
                    % (len(remaining_mounts),
                       remaining_mounts))

    # Release lock

    if do_lock:
        lock_status = release_file_lock(configuration, lock)
        if not lock_status:
            retval = False
            logger.error("Failed to release snapshot lock")

    return (retval, umounted)
